package com.tizz.signin.utils;

import java.util.ArrayList;

public class ArraylistUtils {
    private static ArrayList<String> arrayList=new ArrayList<>();

    public static ArrayList<String> getArrayList(){
        arrayList.add("哲学");
        arrayList.add("经济学");
        arrayList.add("财政学");
        arrayList.add("金融学");
        arrayList.add("经济与贸易");
        arrayList.add("法学");
        arrayList.add("政治学");
        arrayList.add("社会学");
        arrayList.add("民族学");
        arrayList.add("马克思主义理论");
        arrayList.add("公安学");
        arrayList.add("教育学");
        arrayList.add("体育学");
        arrayList.add("中国语言文学");
        arrayList.add("外国语言文学");
        arrayList.add("新闻传播学");
        arrayList.add("历史学");
        arrayList.add("数学");
        arrayList.add("物理学");
        arrayList.add("化学");
        arrayList.add("天文学");
        arrayList.add("地理科学");
        arrayList.add("大气科学");
        arrayList.add("海洋科学");
        arrayList.add("地球物理学");
        arrayList.add("地质学");
        arrayList.add("生物科学");
        arrayList.add("心理学");
        arrayList.add("统计学");
        arrayList.add("力学");
        arrayList.add("机械");
        arrayList.add("仪器");
        arrayList.add("材料");
        arrayList.add("能源动力");
        arrayList.add("电气");
        arrayList.add("电子信息");
        arrayList.add("自动化");
        arrayList.add("计算机");
        arrayList.add("土木");
        arrayList.add("水利");
        arrayList.add("测绘");
        arrayList.add("化工与制药");
        arrayList.add("地质");
        arrayList.add("矿业");
        arrayList.add("纺织");
        arrayList.add("轻工");
        arrayList.add("交通运输");
        arrayList.add("海洋工程");
        arrayList.add("航空航天");
        arrayList.add("兵器");
        arrayList.add("核工程");
        arrayList.add("农业工程");
        arrayList.add("林业工程");
        arrayList.add("环境科学与工程");
        arrayList.add("生物医学工程");
        arrayList.add("食品科学与工程");
        arrayList.add("建筑");
        arrayList.add("安全科学与工程");
        arrayList.add("生物工程");
        arrayList.add("公安技术");
        arrayList.add("植物生产");
        arrayList.add("自然保护与环境生态");
        arrayList.add("动物生产");
        arrayList.add("动物医学");
        arrayList.add("林学");
        arrayList.add("水产");
        arrayList.add("草学");
        arrayList.add("基础医学");
        arrayList.add("临床医学");
        arrayList.add("口腔医学");
        arrayList.add("公共卫生与预防医学");
        arrayList.add("中医学");
        arrayList.add("中西医结合");
        arrayList.add("药学");
        arrayList.add("中药学");
        arrayList.add("法医学");
        arrayList.add("医学技术");
        arrayList.add("护理学");
        arrayList.add("管理科学与工程");
        arrayList.add("工商管理");
        arrayList.add("农业经济管理");
        arrayList.add("公共管理");
        arrayList.add("图书情报与档案管理");
        arrayList.add("物流管理与工程");
        arrayList.add("电子商务");
        arrayList.add("旅游管理");
        arrayList.add("艺术学理论");
        arrayList.add("音乐与舞蹈学");
        arrayList.add("戏剧与影视学");
        arrayList.add("美术学");
        arrayList.add("设计学");
        arrayList.add("院系专业");

        return arrayList;
    }
}
